#ifndef RICO_INPUT_H
#define RICO_INPUT_H

#include "const.h"

typedef u16 rico_key;

struct rico_keychord
{
    rico_key keys[3];
};

#define CHORD3(k0, k1, k2) (struct rico_keychord) {{ k0, k1, k2 }};
#define CHORD2(k0, k1) CHORD3(k0, k1, 0)
#define CHORD1(k0)     CHORD3(k0, 0, 0)

#if 0
struct rico_keysequence
{
    struct rico_keychord chords[3];
};

// NOTE: Key, chord, sequence
struct rico_keyevent
{
    enum rico_keyevent_type
    {
        RICO_KEYEVENT_KEY,
        RICO_KEYEVENT_CHORD,
        RICO_KEYEVENT_SEQUENCE
    } type;
    union
    {
        rico_key key;
        struct rico_keychord chord;
        struct rico_keysequence sequence;
    };
};

#define EVENT (struct rico_keyevent)
#define EVENT_KEY(key) EVENT{ RICO_KEYEVENT_KEY, key }
#define EVENT_CHORD(k0, k1) EVENT{ RICO_KEYEVENT_CHORD, k0, k1 }
#endif

enum rico_action
{
    ACTION_ENGINE_DEBUG_LIGHTING_TOGGLE,
    ACTION_ENGINE_DEBUG_TRIGGER_BREAKPOINT,
    ACTION_ENGINE_FPS_TOGGLE,
    ACTION_ENGINE_MOUSE_LOCK_TOGGLE,
    ACTION_ENGINE_VSYNC_TOGGLE,
    ACTION_ENGINE_MUTE_TOGGLE,
    ACTION_ENGINE_QUIT,

    ACTION_CAMERA_SLOW_TOGGLE,
    ACTION_CAMERA_RESET,
    ACTION_CAMERA_LOCK_TOGGLE,
    ACTION_CAMERA_WIREFRAME_TOGGLE,

    ACTION_MOVE_RIGHT,
    ACTION_MOVE_LEFT,
    ACTION_MOVE_UP,
    ACTION_MOVE_DOWN,
    ACTION_MOVE_FORWARD,
    ACTION_MOVE_BACKWARD,
    ACTION_MOVE_SPRINT,

    ACTION_PLAY_EDITOR,
    ACTION_PLAY_INTERACT,

    ACTION_EDIT_QUIT,
    ACTION_EDIT_SAVE,
    ACTION_EDIT_CYCLE,
    ACTION_EDIT_CYCLE_REVERSE,
    ACTION_EDIT_MOUSE_PICK,
    ACTION_EDIT_BBOX_RECALCULATE,
    ACTION_EDIT_CREATE_OBJECT,
    ACTION_EDIT_SELECTED_DUPLICATE,
    ACTION_EDIT_SELECTED_DELETE,
    ACTION_EDIT_MODE_NEXT,
    ACTION_EDIT_MODE_PREVIOUS,

    ACTION_EDIT_TRANSLATE_RESET,
    ACTION_EDIT_TRANSLATE_UP,
    ACTION_EDIT_TRANSLATE_DOWN,
    ACTION_EDIT_TRANSLATE_WEST,
    ACTION_EDIT_TRANSLATE_EAST,
    ACTION_EDIT_TRANSLATE_NORTH,
    ACTION_EDIT_TRANSLATE_SOUTH,
    ACTION_EDIT_TRANSLATE_DELTA_INCREASE,
    ACTION_EDIT_TRANSLATE_DELTA_DECREASE,

    ACTION_EDIT_ROTATE_RESET,
    ACTION_EDIT_ROTATE_UP,
    ACTION_EDIT_ROTATE_DOWN,
    ACTION_EDIT_ROTATE_WEST,
    ACTION_EDIT_ROTATE_EAST,
    ACTION_EDIT_ROTATE_NORTH,
    ACTION_EDIT_ROTATE_SOUTH,
    ACTION_EDIT_ROTATE_DELTA_INCREASE,
    ACTION_EDIT_ROTATE_DELTA_DECREASE,
    ACTION_EDIT_ROTATE_HEPTAMODE_TOGGLE,

    ACTION_EDIT_SCALE_RESET,
    ACTION_EDIT_SCALE_UP,
    ACTION_EDIT_SCALE_DOWN,
    ACTION_EDIT_SCALE_WEST,
    ACTION_EDIT_SCALE_EAST,
    ACTION_EDIT_SCALE_NORTH,
    ACTION_EDIT_SCALE_SOUTH,
    ACTION_EDIT_SCALE_DELTA_INCREASE,
    ACTION_EDIT_SCALE_DELTA_DECREASE,

    ACTION_EDIT_MATERIAL_NEXT,
    ACTION_EDIT_MATERIAL_PREVIOUS,

    ACTION_EDIT_MESH_NEXT,
    ACTION_EDIT_MESH_PREVIOUS,
    ACTION_EDIT_MESH_BBOX_RECALCULATE,

    ACTION_COUNT
};

#endif